[tool.poetry]
name = "revolutiontech.ca"
version = "0.1.0"
description = "Revolution Technologies website"
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2"
zappa = "^0.48.2"
Pillow = "^6.0.0"
django-classbasedsettings = "^1.5.0"
python-memcached = "^1.59"
sorl-thumbnail = "^12.5.0"
django-ordered-model = "^3.1.1"
django-s3-storage = "^0.12.4"
zappa-django-utils = "^0.4.0"

[tool.poetry.dev-dependencies]
coverage = "^4.5.3"
django-pigeon = "^0.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
