# Generated by Django 3.0.5 on 2020-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basecategory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="css_class",
            field=models.CharField(max_length=15, verbose_name="CSS class"),
        ),
    ]
