# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 00:08
from django.db import migrations


class Migration(migrations.Migration):

    def set_initial_orders(apps, schema_editor):
        GameCategory = apps.get_model("games", "GameCategory")
        for category in GameCategory.objects.all():
            category.order = category.id
            category.save()
        Game = apps.get_model("games", "Game")
        for game in Game.objects.all():
            game.order = game.id
            game.save()

    dependencies = [
        ('games', '0005_auto_20150811_0639'),
    ]

    operations = [
        migrations.RunPython(set_initial_orders, lambda *args: None),
    ]
