name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install

      - run: poetry run inv ci-deploy
        env:
          DECRYPT_PASSWORD: ${{ secrets.DECRYPT_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REVOLUTIONTECH_AWS_ACCESS_KEY_ID: ${{ secrets.REVOLUTIONTECH_AWS_ACCESS_KEY_ID }}
          REVOLUTIONTECH_AWS_SECRET_ACCESS_KEY: ${{ secrets.REVOLUTIONTECH_AWS_SECRET_ACCESS_KEY }}
