# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def set_initial_orders(apps, schema_editor):
        ProductionCategory = apps.get_model("productions", "ProductionCategory")
        for category in ProductionCategory.objects.all():
            category.order = category.id
            category.save()
        Production = apps.get_model("productions", "Production")
        for production in Production.objects.all():
            production.order = production.id
            production.save()

    dependencies = [
        ('productions', '0005_auto_20150811_0639'),
    ]

    operations = [
        migrations.RunPython(set_initial_orders, lambda *args: None),
    ]
